# Minimal example of the importance of specifying data types for CSVs

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
# Reading the file as a csv, without specifying data types leads to a warning about mixed types for 'ncap_rating'. This can create issues with using 'ncap_rating' in later steps.
df_csv_default = pd.read_csv('Datasets/insurance_claims_ncap.csv')
print('Dimensions:', df_csv_default.shape)
display(df_csv_default.head())
display(df_csv_default.info())
print(df_csv_default['ncap_rating'].unique())

Dimensions: (58592, 41)

  df_csv_default = pd.read_csv('Datasets/insurance_claims_ncap.csv')

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,max_power,engine_type,airbags,is_esc,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera,rear_brakes_type,displacement,cylinder,transmission_type,steering_type,turning_radius,length,width,gross_weight,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,claim_status,ncap_rating
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,0,3
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,97.89bhp@3600rpm,i-DTEC,2,No,Yes,No,Yes,Yes,Drum,1498,4,Manual,Electric,4.9,3995,1695,1051,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,4
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,0,3
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,Power,4.6,3445,1515,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,88.77bhp@4000rpm,1.5 Turbocharged Revotorq,2,No,Yes,No,Yes,No,Drum,1497,4,Manual,Electric,5.0,3990,1755,1490,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,Yes,0,5

<class 'pandas.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  str
 1   subscription_length               58592 non-null  float64
 2   vehicle_age                       58592 non-null  float64
 3   customer_age                      58592 non-null  int64
 4   region_code                       58592 non-null  str
 5   region_density                    58592 non-null  int64
 6   segment                           58592 non-null  str
 7   model                             58592 non-null  str
 8   fuel_type                         58592 non-null  str
 9   max_torque                        58592 non-null  str
 10  max_power                         58592 non-null  str
 11  engine_type                       58592 non-null  str
 12  airbags                           58592 non-null  int64
 13  is_esc                            58592 non-null  str
 14  is_adjustable_steering            58592 non-null  str
 15  is_tpms                           58592 non-null  str
 16  is_parking_sensors                58592 non-null  str
 17  is_parking_camera                 58592 non-null  str
 18  rear_brakes_type                  58592 non-null  str
 19  displacement                      58592 non-null  int64
 20  cylinder                          58592 non-null  int64
 21  transmission_type                 58592 non-null  str
 22  steering_type                     58592 non-null  str
 23  turning_radius                    58592 non-null  float64
 24  length                            58592 non-null  int64
 25  width                             58592 non-null  int64
 26  gross_weight                      58592 non-null  int64
 27  is_front_fog_lights               58592 non-null  str
 28  is_rear_window_wiper              58592 non-null  str
 29  is_rear_window_washer             58592 non-null  str
 30  is_rear_window_defogger           58592 non-null  str
 31  is_brake_assist                   58592 non-null  str
 32  is_power_door_locks               58592 non-null  str
 33  is_central_locking                58592 non-null  str
 34  is_power_steering                 58592 non-null  str
 35  is_driver_seat_height_adjustable  58592 non-null  str
 36  is_day_night_rear_view_mirror     58592 non-null  str
 37  is_ecw                            58592 non-null  str
 38  is_speed_alert                    58592 non-null  str
 39  claim_status                      58592 non-null  int64
 40  ncap_rating                       58592 non-null  object
dtypes: float64(3), int64(9), object(1), str(28)
memory usage: 25.3+ MB

None

[3 4 0 5 2 '3' '2' '5' '0' '4' 'NR']

In [3]:
# Reading the file as a parquet
df_parquet = pd.read_parquet('Datasets/insurance_claims_ncap.parquet')
print('Dimensions:', df_parquet.shape)
display(df_parquet.head())
display(df_parquet.info())
print(df_parquet['ncap_rating'].unique())

Dimensions: (58592, 41)

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,max_power,engine_type,airbags,is_esc,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera,rear_brakes_type,displacement,cylinder,transmission_type,steering_type,turning_radius,length,width,gross_weight,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,claim_status,ncap_rating
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,0,3
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,97.89bhp@3600rpm,i-DTEC,2,No,Yes,No,Yes,Yes,Drum,1498,4,Manual,Electric,4.9,3995,1695,1051,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,4
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,0,3
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,Power,4.6,3445,1515,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,88.77bhp@4000rpm,1.5 Turbocharged Revotorq,2,No,Yes,No,Yes,No,Drum,1497,4,Manual,Electric,5.0,3990,1755,1490,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,Yes,0,5

<class 'pandas.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  str
 1   subscription_length               58592 non-null  float64
 2   vehicle_age                       58592 non-null  float64
 3   customer_age                      58592 non-null  int64
 4   region_code                       58592 non-null  str
 5   region_density                    58592 non-null  int64
 6   segment                           58592 non-null  str
 7   model                             58592 non-null  str
 8   fuel_type                         58592 non-null  str
 9   max_torque                        58592 non-null  str
 10  max_power                         58592 non-null  str
 11  engine_type                       58592 non-null  str
 12  airbags                           58592 non-null  int64
 13  is_esc                            58592 non-null  str
 14  is_adjustable_steering            58592 non-null  str
 15  is_tpms                           58592 non-null  str
 16  is_parking_sensors                58592 non-null  str
 17  is_parking_camera                 58592 non-null  str
 18  rear_brakes_type                  58592 non-null  str
 19  displacement                      58592 non-null  int64
 20  cylinder                          58592 non-null  int64
 21  transmission_type                 58592 non-null  str
 22  steering_type                     58592 non-null  str
 23  turning_radius                    58592 non-null  float64
 24  length                            58592 non-null  int64
 25  width                             58592 non-null  int64
 26  gross_weight                      58592 non-null  int64
 27  is_front_fog_lights               58592 non-null  str
 28  is_rear_window_wiper              58592 non-null  str
 29  is_rear_window_washer             58592 non-null  str
 30  is_rear_window_defogger           58592 non-null  str
 31  is_brake_assist                   58592 non-null  str
 32  is_power_door_locks               58592 non-null  str
 33  is_central_locking                58592 non-null  str
 34  is_power_steering                 58592 non-null  str
 35  is_driver_seat_height_adjustable  58592 non-null  str
 36  is_day_night_rear_view_mirror     58592 non-null  str
 37  is_ecw                            58592 non-null  str
 38  is_speed_alert                    58592 non-null  str
 39  claim_status                      58592 non-null  int64
 40  ncap_rating                       58592 non-null  str
dtypes: float64(3), int64(9), str(29)
memory usage: 25.3 MB

None

<ArrowStringArray>
['3', '4', '0', '5', '2', 'NR']
Length: 6, dtype: str

In [4]:
# Setting explicit data types when reading as csv. Note that 'ncap_rating' is specified as a string.

data_types = {
	'policy_id': 'str',
	'subscription_length': 'float',
	'vehicle_age': 'float',
	'customer_age': 'int',
	'region_code': 'str',
	'region_density': 'int',
	'segment': 'str',
	'model': 'str',
	'fuel_type': 'str',
	'max_torque': 'str',
	'max_power': 'str',
	'engine_type': 'str',
	'airbags': 'int',
	'is_esc': 'str',
	'is_adjustable_steering': 'str',
	'is_tpms': 'str',
	'is_parking_sensors': 'str',
	'is_parking_camera': 'str',
	'rear_brakes_type': 'str',
	'displacement': 'int',
	'cylinder': 'int',
	'transmission_type': 'str',
	'steering_type': 'str',
	'turning_radius': 'float',
	'length': 'int',
	'width': 'int',
	'gross_weight': 'int',
	'is_front_fog_lights': 'str',
	'is_rear_window_wiper': 'str',
	'is_rear_window_washer': 'str',
	'is_rear_window_defogger': 'str',
	'is_brake_assist': 'str',
	'is_power_door_locks': 'str',
	'is_central_locking': 'str',
	'is_power_steering': 'str',
	'is_driver_seat_height_adjustable': 'str',
	'is_day_night_rear_view_mirror': 'str',
	'is_ecw': 'str',
	'is_speed_alert': 'str',
	'claim_status': 'int',
	'ncap_rating': 'str'
}

df_csv_typed = pd.read_csv('Datasets/insurance_claims_ncap.csv', dtype=data_types)
print('Dimensions:', df_csv_typed.shape)
display(df_csv_typed.head())
display(df_csv_typed.info())
print(df_csv_typed['ncap_rating'].unique())

Dimensions: (58592, 41)

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,max_power,engine_type,airbags,is_esc,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera,rear_brakes_type,displacement,cylinder,transmission_type,steering_type,turning_radius,length,width,gross_weight,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,claim_status,ncap_rating
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,0,3
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,97.89bhp@3600rpm,i-DTEC,2,No,Yes,No,Yes,Yes,Drum,1498,4,Manual,Electric,4.9,3995,1695,1051,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,4
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,0,3
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,Power,4.6,3445,1515,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,88.77bhp@4000rpm,1.5 Turbocharged Revotorq,2,No,Yes,No,Yes,No,Drum,1497,4,Manual,Electric,5.0,3990,1755,1490,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,Yes,0,5

<class 'pandas.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  str
 1   subscription_length               58592 non-null  float64
 2   vehicle_age                       58592 non-null  float64
 3   customer_age                      58592 non-null  int64
 4   region_code                       58592 non-null  str
 5   region_density                    58592 non-null  int64
 6   segment                           58592 non-null  str
 7   model                             58592 non-null  str
 8   fuel_type                         58592 non-null  str
 9   max_torque                        58592 non-null  str
 10  max_power                         58592 non-null  str
 11  engine_type                       58592 non-null  str
 12  airbags                           58592 non-null  int64
 13  is_esc                            58592 non-null  str
 14  is_adjustable_steering            58592 non-null  str
 15  is_tpms                           58592 non-null  str
 16  is_parking_sensors                58592 non-null  str
 17  is_parking_camera                 58592 non-null  str
 18  rear_brakes_type                  58592 non-null  str
 19  displacement                      58592 non-null  int64
 20  cylinder                          58592 non-null  int64
 21  transmission_type                 58592 non-null  str
 22  steering_type                     58592 non-null  str
 23  turning_radius                    58592 non-null  float64
 24  length                            58592 non-null  int64
 25  width                             58592 non-null  int64
 26  gross_weight                      58592 non-null  int64
 27  is_front_fog_lights               58592 non-null  str
 28  is_rear_window_wiper              58592 non-null  str
 29  is_rear_window_washer             58592 non-null  str
 30  is_rear_window_defogger           58592 non-null  str
 31  is_brake_assist                   58592 non-null  str
 32  is_power_door_locks               58592 non-null  str
 33  is_central_locking                58592 non-null  str
 34  is_power_steering                 58592 non-null  str
 35  is_driver_seat_height_adjustable  58592 non-null  str
 36  is_day_night_rear_view_mirror     58592 non-null  str
 37  is_ecw                            58592 non-null  str
 38  is_speed_alert                    58592 non-null  str
 39  claim_status                      58592 non-null  int64
 40  ncap_rating                       58592 non-null  str
dtypes: float64(3), int64(9), str(29)
memory usage: 25.3 MB

None

<ArrowStringArray>
['3', '4', '0', '5', '2', 'NR']
Length: 6, dtype: str